### ISSUE TITLE
Simplify Manager Testing

### ISSUE THREAD

**Issue by drasko** [ultravioletrs/cocos#102]
### Is your feature request related to a problem? Please describe.

No

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Check if we can test everything just using [grpcurl](https://github.com/fullstorydev/grpcurl).

If yes, then please remove the `manager-server` code (to lower complexity), and document the testing procedure via `grpcurl` tool in our official documentation.

### Indicate the importance of this feature to you.

Must-have

**Comment by SammyOina** [comment]
@drasko we cannot use this with manager since it is the client. grpcurl is also a client. We could use it with agent but agent already has cli so there seems no need to add this. For now it seems we're stuck with the example manager-server but we can certainly improve it or even possibly make it an interactive shell and allow the user to add requests in the deamon.
